name: "Helm Chart Releaser"
description: "Create Helm chart releases"
author: "Patrick Kerwood"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.6.1)"
    required: false
    default: v1.6.1

  github_token:
    description: "Github token"
    required: true

  charts_dir:
    description: "The charts directory"
    required: false
    default: charts

  mark_as_latest:
    description: Mark the created GitHub release as 'latest'
    required: false
    default: true

  generate_release_notes:
    description: "Auto generate release notes"
    required: false
    default: true

  pages_branch:
    description: "Name of the branch to be used to push the index and artifacts. (default to: gh-pages but it is not set in the action it is a default value for the chart-releaser binary)"
    required: false
    default: gh-pages

runs:
  using: composite
  steps:
    - id: action-path
      name: Adding action path to $PATH
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - id: install-chart-releaser
      name: Install Chart Releaser
      working-directory: ${{ github.action_path }}
      shell: bash
      run: download-cr.sh --cr-version ${{ inputs.version }}

    - id: package-charts
      name: Package Charts
      shell: bash
      run: package-charts.sh --charts-dir ${{ inputs.charts_dir }}

    - id: release-charts
      name: Release Charts
      if: env.CHARTS_PACKAGED == 'true'
      shell: bash
      run: release-charts.sh -r $GITHUB_REPOSITORY -t ${{ inputs.github_token }} -m ${{ inputs.mark_as_latest }} -g ${{ inputs.generate_release_notes }}

    - id: update-index
      name: Update Index
      if: env.CHARTS_PACKAGED == 'true'
      shell: bash
      run: update-index.sh -r $GITHUB_REPOSITORY -t ${{ inputs.github_token }} -p ${{ inputs.pages_branch }}
